import type { PromptTemplate } from "./types";

export const BUILT_IN_PROMPTS: PromptTemplate[] = [
  {
    id: "builtin_explain",
    label: "Explain what you did",
    prompt: "Explain what you did",
    icon: "💡",
    category: "general",
    isBuiltIn: true,
    sortOrder: 0,
    statusFilter: ["idle", "completed", "failed"],
  },
  {
    id: "builtin_changes",
    label: "Show changes",
    prompt: "Show me the changes you made",
    icon: "📝",
    category: "general",
    isBuiltIn: true,
    sortOrder: 1,
    statusFilter: ["idle", "completed", "failed"],
  },
  {
    id: "builtin_tests",
    label: "Run tests",
    prompt: "Run the tests",
    icon: "🧪",
    category: "test",
    isBuiltIn: true,
    sortOrder: 2,
  },
  {
    id: "builtin_continue",
    label: "Continue",
    prompt: "Continue",
    icon: "▶️",
    category: "general",
    isBuiltIn: true,
    sortOrder: 3,
  },
  {
    id: "builtin_undo",
    label: "Undo last change",
    prompt: "Undo the last change you made",
    icon: "↩️",
    category: "general",
    isBuiltIn: true,
    sortOrder: 4,
    statusFilter: ["idle", "completed", "failed"],
  },
  {
    id: "builtin_review",
    label: "Review for bugs",
    prompt: "Review the code for bugs and potential issues",
    icon: "🔍",
    category: "review",
    isBuiltIn: true,
    sortOrder: 5,
  },
  {
    id: "builtin_refactor",
    label: "Suggest refactoring",
    prompt: "Suggest refactoring improvements for the code",
    icon: "♻️",
    category: "refactor",
    isBuiltIn: true,
    sortOrder: 6,
  },
  {
    id: "builtin_status",
    label: "Current status",
    prompt: "What is the current status? Summarize what has been done and what remains.",
    icon: "📊",
    category: "general",
    isBuiltIn: true,
    sortOrder: 7,
  },
  {
    id: "builtin_commit",
    label: "Commit changes",
    prompt: "Commit the changes with an appropriate commit message",
    icon: "💾",
    category: "general",
    isBuiltIn: true,
    sortOrder: 8,
    statusFilter: ["idle", "completed"],
  },
  {
    id: "builtin_explain_error",
    label: "Explain error",
    prompt: "Explain the error and suggest how to fix it",
    icon: "❓",
    category: "debug",
    isBuiltIn: true,
    sortOrder: 9,
    statusFilter: ["failed"],
  },
];
