import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

export type DeployProxy = "caddy" | "nginx" | "none";

export interface DeployScaffoldOptions {
  outputDir: string;
  domain?: string;
  publicOrigin?: string;
  email?: string;
  proxy: DeployProxy;
  serviceName: string;
  daemonUser: string;
  bridgePort: number;
  bindHost: string;
  defaultCwd?: string;
  evenAiTool?: "claude" | "codex" | "gemini";
  evenAiMode?: "new" | "last" | "pinned";
}

export interface DeployScaffoldResult {
  rootDir: string;
  files: string[];
}

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(target: string, content: string, mode?: number): string {
  ensureDir(path.dirname(target));
  fs.writeFileSync(target, content, { encoding: "utf-8", mode });
  if (mode != null) {
    fs.chmodSync(target, mode);
  }
  return target;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function renderSystemdService(opts: DeployScaffoldOptions): string {
  const homeDir = opts.daemonUser === "root"
    ? "/root"
    : opts.daemonUser === os.userInfo().username
      ? os.homedir()
      : `/home/${opts.daemonUser}`;
  return `[Unit]
Description=OpenVide daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${opts.daemonUser}
WorkingDirectory=${homeDir}
Environment=HOME=${homeDir}
ExecStart=/usr/bin/env openvide-daemon run
Restart=always
RestartSec=2
TimeoutStopSec=20
KillSignal=SIGTERM

[Install]
WantedBy=multi-user.target
`;
}

function renderCaddyfile(opts: DeployScaffoldOptions): string {
  if (!opts.domain) {
    throw new Error("--domain is required for proxy mode");
  }
  const tlsBlock = opts.email?.trim()
    ? `\n  tls ${opts.email.trim()}\n`
    : "\n";

  return `${opts.domain} {${tlsBlock}  reverse_proxy http://${opts.bindHost}:${opts.bridgePort}
}
`;
}

function renderNginxConfig(opts: DeployScaffoldOptions): string {
  if (!opts.domain) {
    throw new Error("--domain is required for proxy mode");
  }
  return `server {
  listen 80;
  listen [::]:80;
  server_name ${opts.domain};

  location / {
    proxy_pass http://${opts.bindHost}:${opts.bridgePort};
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
`;
}

function renderBootstrapScript(opts: DeployScaffoldOptions): string {
  const lines = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
  ];

  if (opts.proxy === "none") {
    lines.push(`openvide-daemon bridge enable --port ${opts.bridgePort}`);
  } else {
    lines.push(`openvide-daemon bridge enable --port ${opts.bridgePort} --no-tls`);
  }

  const configParts = [
    "openvide-daemon bridge config",
    `--bind-host ${shellQuote(opts.bindHost)}`,
  ];
  if (opts.defaultCwd?.trim()) {
    configParts.push(`--default-cwd ${shellQuote(opts.defaultCwd.trim())}`);
  }
  if (opts.evenAiTool) {
    configParts.push(`--even-ai-tool ${opts.evenAiTool}`);
  }
  if (opts.evenAiMode) {
    configParts.push(`--even-ai-mode ${opts.evenAiMode}`);
  }
  lines.push(configParts.join(" "));
  lines.push("openvide-daemon bridge status");
  lines.push('echo ""');
  lines.push('echo "Issue a client token with: openvide-daemon bridge token --expire 24h"');
  lines.push('echo "Bridge runtime data lives under: ~/.openvide-daemon"');
  lines.push("");

  return lines.join("\n");
}

function renderScaffoldReadme(opts: DeployScaffoldOptions, generatedFiles: string[]): string {
  const origin = opts.publicOrigin
    ?? (opts.domain ? `https://${opts.domain}` : `https://YOUR_HOST:${opts.bridgePort}`);
  const proxyFile = opts.proxy === "caddy"
    ? "proxy/Caddyfile"
    : opts.proxy === "nginx"
      ? "proxy/openvide.conf"
      : null;

  const copyProxyBlock = proxyFile == null
    ? `4. The bridge uses its own TLS. Make sure clients trust the self-signed certificate or replace it with your own trusted TLS setup.`
    : opts.proxy === "caddy"
      ? `4. Copy ${proxyFile} to \`/etc/caddy/Caddyfile\` and reload Caddy.`
      : `4. Copy ${proxyFile} to your nginx sites configuration and reload nginx.`;

  return `# OpenVide Self-Host Scaffold

This directory was generated by:

\`\`\`bash
openvide-daemon deploy scaffold ...
\`\`\`

It gives you the operator files needed to run OpenVide on your own host or VPS.

## Generated Files

${generatedFiles.map((file) => `- \`${file}\``).join("\n")}

## Recommended Topology

\`\`\`text
browser / webview / Even AI
  -> ${origin}
  -> ${opts.proxy === "none" ? "openvide-daemon bridge" : `${opts.proxy} reverse proxy`}
  -> openvide-daemon bridge on ${opts.bindHost}:${opts.bridgePort}
\`\`\`

## Why This Setup

- the daemon stays managed by \`systemd\`
- JWT bridge auth remains enabled
- ${opts.proxy === "none"
    ? "the daemon serves TLS directly"
    : "public TLS is handled by a trusted reverse proxy"}
- the daemon bridge binds to \`${opts.bindHost}\`

## Install Steps

1. Install the daemon globally on the host:

\`\`\`bash
npm install -g @openvide/daemon
\`\`\`

2. Install the systemd unit:

\`\`\`bash
sudo cp systemd/${opts.serviceName}.service /etc/systemd/system/${opts.serviceName}.service
sudo systemctl daemon-reload
sudo systemctl enable --now ${opts.serviceName}
\`\`\`

3. Configure the bridge runtime:

\`\`\`bash
./bootstrap-bridge.sh
\`\`\`

${copyProxyBlock}

5. Issue a token for clients:

\`\`\`bash
openvide-daemon bridge token --expire 24h
\`\`\`

6. For Even AI custom agents, use:

\`\`\`text
${origin}/v1/chat/completions
\`\`\`

## Notes

- Runtime state is stored in \`~/.openvide-daemon\`
- If you use ${opts.proxy === "none" ? "built-in TLS directly" : "a reverse proxy"}, keep bridge JWT auth enabled
- If you generated bridge certs before the latest SAN changes, rotate:
  - \`~/.openvide-daemon/bridge/cert.pem\`
  - \`~/.openvide-daemon/bridge/key.pem\`
`;
}

export function generateDeployScaffold(opts: DeployScaffoldOptions): DeployScaffoldResult {
  const rootDir = path.resolve(opts.outputDir);
  ensureDir(rootDir);

  const writtenFiles: string[] = [];
  writtenFiles.push(
    path.relative(rootDir, writeFile(
      path.join(rootDir, "systemd", `${opts.serviceName}.service`),
      renderSystemdService(opts),
      0o644,
    )),
  );

  writtenFiles.push(
    path.relative(rootDir, writeFile(
      path.join(rootDir, "bootstrap-bridge.sh"),
      renderBootstrapScript(opts),
      0o755,
    )),
  );

  if (opts.proxy === "caddy") {
    writtenFiles.push(
      path.relative(rootDir, writeFile(
        path.join(rootDir, "proxy", "Caddyfile"),
        renderCaddyfile(opts),
        0o644,
      )),
    );
  } else if (opts.proxy === "nginx") {
    writtenFiles.push(
      path.relative(rootDir, writeFile(
        path.join(rootDir, "proxy", "openvide.conf"),
        renderNginxConfig(opts),
        0o644,
      )),
    );
  }

  writtenFiles.push("README.md");
  writtenFiles.push(
    path.relative(rootDir, writeFile(
      path.join(rootDir, "README.md"),
      renderScaffoldReadme(opts, writtenFiles),
      0o644,
    )),
  );

  return { rootDir, files: [...new Set(writtenFiles)] };
}
